# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HazelcastCommandlineClient < Formula
  desc "Hazelcast Command-line Client Project"
  homepage "https://github.com/hazelcast/hazelcast-commandline-client"
  version "0.0.1-goreleaser"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v0.0.1-goreleaser/hazelcast-commandline-client_0.0.1-goreleaser_Darwin_arm64.tar.gz"
      sha256 "3b1d95818a04da2b8cce2dc564254832579be57e8c8a5cfe3d5872fc96a6e123"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v0.0.1-goreleaser/hazelcast-commandline-client_0.0.1-goreleaser_Darwin_x86_64.tar.gz"
      sha256 "bf3f6974f6d1f9711394aca091d75849006151f33c35ab264f32077d8c8d36b6"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v0.0.1-goreleaser/hazelcast-commandline-client_0.0.1-goreleaser_Linux_arm64.tar.gz"
      sha256 "835940fd72baea5bac6951952717659e48051fe12603bbdfb1596ac403c628e6"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v0.0.1-goreleaser/hazelcast-commandline-client_0.0.1-goreleaser_Linux_x86_64.tar.gz"
      sha256 "2ac347b789b83e710e4bee637defdad929fba065f1698ad2283ef05585789066"

      def install
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  def post_install
    ohai "Example usages:
    * `hzc` - start an interactive shell 🚀
    * `hzc map --name my-map put --key hello --value world` - put entry into map"
        completion_warning = <<~EOS
          ⚠️  To have superior experience, enable autocompletion on Brew. ⚠️
          You need to enable autocompletion just once for Brew. If it is already enabled, you can skip this part.
          ▪ For Bash users:
            1) `brew install bash-completion` and follow the printed \"Caveats\" section. Example \"Caveats\" instructions:
               Add the following line to your ~/.bash_profile:
               # !! Note that paths may differ depending on your installation, so you should follow the Caveats section on your system.
               [[ -r \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\" ]] && . \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\"
            2) `source ~/.bash_profile`
          ▪ For Zsh users:
          Follow https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
        EOS
        print completion_warning
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
