# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HazelcastCommandlineClient < Formula
  desc "Hazelcast Command-line Client Project"
  homepage "https://github.com/hazelcast/hazelcast-commandline-client"
  version "0.0.1-goreleaser"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v0.0.1-goreleaser/hz-cli_0.0.1-goreleaser_Darwin_x86_64"
      sha256 "6d060189e6f4d0af4e0bdedb0e4b74b5fbd0cdd80a80d8203834e0d3e255690a"

      def install
        system "make"
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v0.0.1-goreleaser/hz-cli_0.0.1-goreleaser_Darwin_arm64"
      sha256 "1bb3044997b9942c1f2d7332b269e062502aec680d8cdf47fbdc30c803a419d1"

      def install
        system "make"
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v0.0.1-goreleaser/hz-cli_0.0.1-goreleaser_Linux_x86_64"
      sha256 "9a0f1541fc2dba48246a3c82b49f315036c6c73b60b2f49c1e720cd6c6fac388"

      def install
        system "make"
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/utku-caglayan/hazelcast-commandline-client/releases/download/v0.0.1-goreleaser/hz-cli_0.0.1-goreleaser_Linux_arm64"
      sha256 "eaa858f04eafa1241001ba39e8c753bfbe16a46fba858282027fa8d5c0469a51"

      def install
        system "make"
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  def post_install
    ohai "Example usages:
    * `hzc` - start an interactive shell 🚀
    * `hzc map --name my-map put --key hello --value world` - put entry into map"
        completion_warning = <<~EOS
          ⚠️  To have superior experience, enable autocompletion on Brew. ⚠️
          You need to enable autocompletion just once for Brew. If it is already enabled, you can skip this part.
          ▪ For Bash users:
            1) `brew install bash-completion` and follow the printed \"Caveats\" section. Example \"Caveats\" instructions:
               Add the following line to your ~/.bash_profile:
               # !! Note that paths may differ depending on your installation, so you should follow the Caveats section on your system.
               [[ -r \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\" ]] && . \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\"
            2) `source ~/.bash_profile`
          ▪ For Zsh users:
          Follow https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
        EOS
        print completion_warning
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
