# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class HazelcastCommandlineClient < Formula
  desc "Hazelcast Command-line Client Project"
  homepage "https://github.com/hazelcast/hazelcast-commandline-client"
  version "0.0.1-goreleaser"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/v0.0.1-goreleaser/hz-cli_0.0.1-goreleaser_Darwin_x86_64"
      sha256 "b17e42c5229e639ab7dab990f6745c45266a7332f000049388f7754d51310196"

      def install
        system "make"
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/v0.0.1-goreleaser/hz-cli_0.0.1-goreleaser_Darwin_arm64"
      sha256 "05126de0e7ba89639f4fdde7ebd82b7f0692cc0e6f75f1eb254a2e46dfe2c643"

      def install
        system "make"
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/v0.0.1-goreleaser/hz-cli_0.0.1-goreleaser_Linux_x86_64"
      sha256 "031bccb51c39b9c5fe10d9d786917778db02663f8ec7505ad95a05b2c68edcd8"

      def install
        system "make"
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/hazelcast/hazelcast-commandline-client/releases/v0.0.1-goreleaser/hz-cli_0.0.1-goreleaser_Linux_arm64"
      sha256 "f9d8d70ed39704b6a68b5ed01c74439f2bdd31a4298937bd41b7c4128f50f832"

      def install
        system "make"
        bin.install "hzc"
        bash_completion.install "extras/bash_completion.sh"
        zsh_completion.install "extras/zsh_completion.zsh" => "_hzc"
      end
    end
  end

  def post_install
    ohai "Example usages:
    * `hzc` - start an interactive shell 🚀
    * `hzc map --name my-map put --key hello --value world` - put entry into map"
        completion_warning = <<~EOS
          ⚠️  To have superior experience, enable autocompletion on Brew. ⚠️
          You need to enable autocompletion just once for Brew. If it is already enabled, you can skip this part.
          ▪ For Bash users:
            1) `brew install bash-completion` and follow the printed \"Caveats\" section. Example \"Caveats\" instructions:
               Add the following line to your ~/.bash_profile:
               # !! Note that paths may differ depending on your installation, so you should follow the Caveats section on your system.
               [[ -r \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\" ]] && . \"/home/ubuntu/.linuxbrew/etc/profile.d/bash_completion.sh\"
            2) `source ~/.bash_profile`
          ▪ For Zsh users:
          Follow https://docs.brew.sh/Shell-Completion#configuring-completions-in-zsh
        EOS
        print completion_warning
  end

  def caveats; <<~EOS
    How to use this binary
  EOS
  end
end
